export interface Country {
  code: string;
  name: string;
  cities: string[];
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", cities: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Kunduz", "Jalalabad", "Ghazni"] },
  { code: "AL", name: "Albania", cities: ["Tirana", "Durrës", "Vlorë", "Shkodër", "Elbasan", "Korçë"] },
  { code: "DZ", name: "Algeria", cities: ["Algiers", "Oran", "Constantine", "Annaba", "Blida", "Batna", "Sétif", "Sidi Bel Abbès", "Biskra", "Tébessa"] },
  { code: "AD", name: "Andorra", cities: ["Andorra la Vella", "Escaldes-Engordany", "Encamp"] },
  { code: "AO", name: "Angola", cities: ["Luanda", "Huambo", "Lubango", "Cabinda", "Benguela", "Malanje"] },
  { code: "AG", name: "Antigua and Barbuda", cities: ["Saint John's", "All Saints", "Liberta"] },
  { code: "AR", name: "Argentina", cities: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "Tucumán", "La Plata", "Mar del Plata", "Salta", "Santa Fe", "San Juan", "Neuquén", "Resistencia"] },
  { code: "AM", name: "Armenia", cities: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Abovyan"] },
  { code: "AU", name: "Australia", cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra", "Newcastle", "Wollongong", "Hobart", "Darwin", "Cairns", "Townsville", "Geelong"] },
  { code: "AT", name: "Austria", cities: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "St. Pölten"] },
  { code: "AZ", name: "Azerbaijan", cities: ["Baku", "Ganja", "Sumqayit", "Lankaran", "Mingachevir", "Nakhchivan"] },
  { code: "BS", name: "Bahamas", cities: ["Nassau", "Freeport", "Marsh Harbour"] },
  { code: "BH", name: "Bahrain", cities: ["Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali", "Isa Town", "Sitra", "Budaiya"] },
  { code: "BD", name: "Bangladesh", cities: ["Dhaka", "Chittagong", "Sylhet", "Rajshahi", "Khulna", "Comilla", "Mymensingh", "Rangpur", "Bogra", "Narayanganj", "Gazipur"] },
  { code: "BB", name: "Barbados", cities: ["Bridgetown", "Speightstown", "Oistins"] },
  { code: "BY", name: "Belarus", cities: ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest", "Bobruisk"] },
  { code: "BE", name: "Belgium", cities: ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur", "Leuven", "Mons", "Mechelen"] },
  { code: "BZ", name: "Belize", cities: ["Belize City", "Belmopan", "San Ignacio", "Orange Walk"] },
  { code: "BJ", name: "Benin", cities: ["Cotonou", "Porto-Novo", "Parakou", "Abomey-Calavi", "Djougou"] },
  { code: "BT", name: "Bhutan", cities: ["Thimphu", "Phuntsholing", "Paro", "Punakha"] },
  { code: "BO", name: "Bolivia", cities: ["Santa Cruz de la Sierra", "La Paz", "El Alto", "Cochabamba", "Sucre", "Oruro", "Tarija", "Potosí"] },
  { code: "BA", name: "Bosnia and Herzegovina", cities: ["Sarajevo", "Banja Luka", "Mostar", "Tuzla", "Zenica", "Bijeljina"] },
  { code: "BW", name: "Botswana", cities: ["Gaborone", "Francistown", "Molepolole", "Selebi-Phikwe", "Maun", "Serowe"] },
  { code: "BR", name: "Brazil", cities: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Belém", "Goiânia", "Campinas", "São Luís", "Maceió", "Natal", "Teresina", "Campo Grande"] },
  { code: "BN", name: "Brunei", cities: ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong"] },
  { code: "BG", name: "Bulgaria", cities: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven", "Sliven", "Dobrich"] },
  { code: "BF", name: "Burkina Faso", cities: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora"] },
  { code: "BI", name: "Burundi", cities: ["Bujumbura", "Muyinga", "Gitega", "Ngozi", "Rumonge"] },
  { code: "CV", name: "Cabo Verde", cities: ["Praia", "Mindelo", "Santa Maria", "Assomada"] },
  { code: "KH", name: "Cambodia", cities: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Kampong Cham", "Pursat"] },
  { code: "CM", name: "Cameroon", cities: ["Douala", "Yaoundé", "Bamenda", "Bafoussam", "Maroua", "Ngaoundéré", "Garoua"] },
  { code: "CA", name: "Canada", cities: ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Kitchener", "London", "Victoria", "Halifax", "Saskatoon", "Regina", "St. John's", "Kelowna", "Barrie"] },
  { code: "CF", name: "Central African Republic", cities: ["Bangui", "Bimbo", "Mbaïki", "Berberati"] },
  { code: "TD", name: "Chad", cities: ["N'Djamena", "Moundou", "Sarh", "Abéché", "Kélo"] },
  { code: "CL", name: "Chile", cities: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Arica", "Chillán", "Puerto Montt"] },
  { code: "CN", name: "China", cities: ["Shanghai", "Beijing", "Guangzhou", "Shenzhen", "Chengdu", "Chongqing", "Tianjin", "Wuhan", "Xi'an", "Hangzhou", "Nanjing", "Shenyang", "Dongguan", "Zhengzhou", "Qingdao", "Foshan", "Kunming", "Harbin", "Changsha", "Suzhou"] },
  { code: "CO", name: "Colombia", cities: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Soledad", "Ibagué", "Bucaramanga", "Santa Marta", "Villavicencio", "Pereira"] },
  { code: "KM", name: "Comoros", cities: ["Moroni", "Mutsamudu", "Fomboni"] },
  { code: "CD", name: "Congo (DRC)", cities: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Goma", "Bukavu", "Kisangani", "Kananga", "Kolwezi"] },
  { code: "CG", name: "Congo (Republic)", cities: ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi"] },
  { code: "CR", name: "Costa Rica", cities: ["San José", "Alajuela", "Desamparados", "Heredia", "Cartago", "Liberia", "Limón"] },
  { code: "CI", name: "Côte d'Ivoire", cities: ["Abidjan", "Bouaké", "Daloa", "Yamoussoukro", "San-Pédro", "Korhogo", "Man"] },
  { code: "HR", name: "Croatia", cities: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Slavonski Brod", "Pula"] },
  { code: "CU", name: "Cuba", cities: ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Guantánamo", "Santa Clara", "Bayamo"] },
  { code: "CY", name: "Cyprus", cities: ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos", "Kyrenia"] },
  { code: "CZ", name: "Czech Republic", cities: ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc", "Ústí nad Labem", "Hradec Králové", "České Budějovice"] },
  { code: "DK", name: "Denmark", cities: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Frederiksberg", "Esbjerg", "Randers", "Kolding"] },
  { code: "DJ", name: "Djibouti", cities: ["Djibouti City", "Tadjourah", "Obock", "Dikhil"] },
  { code: "DM", name: "Dominica", cities: ["Roseau", "Portsmouth", "Marigot"] },
  { code: "DO", name: "Dominican Republic", cities: ["Santo Domingo", "Santiago", "La Romana", "San Pedro de Macorís", "San Cristóbal", "Higüey", "La Vega"] },
  { code: "EC", name: "Ecuador", cities: ["Guayaquil", "Quito", "Cuenca", "Santo Domingo", "Machala", "Durán", "Manta", "Portoviejo", "Ambato", "Loja"] },
  { code: "EG", name: "Egypt", cities: ["Cairo", "Alexandria", "Giza", "Shubra El-Kheima", "Port Said", "Suez", "Mansoura", "Mahalla el-Kubra", "Tanta", "Asyut", "Ismailia", "Faiyum", "Zagazig", "Luxor", "Aswan", "Damietta", "Sohag", "Hurghada", "Sharm El-Sheikh"] },
  { code: "SV", name: "El Salvador", cities: ["San Salvador", "Soyapango", "Santa Ana", "San Miguel", "Mejicanos", "Apopa"] },
  { code: "GQ", name: "Equatorial Guinea", cities: ["Malabo", "Bata", "Ebebiyín", "Aconibe"] },
  { code: "ER", name: "Eritrea", cities: ["Asmara", "Keren", "Massawa", "Assab", "Mendefera"] },
  { code: "EE", name: "Estonia", cities: ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve", "Viljandi"] },
  { code: "SZ", name: "Eswatini", cities: ["Mbabane", "Manzini", "Lobamba", "Siteki"] },
  { code: "ET", name: "Ethiopia", cities: ["Addis Ababa", "Dire Dawa", "Mek'ele", "Gondar", "Hawassa", "Bahir Dar", "Dessie", "Jimma", "Jijiga", "Shashamane"] },
  { code: "FJ", name: "Fiji", cities: ["Suva", "Lautoka", "Nadi", "Labasa", "Ba"] },
  { code: "FI", name: "Finland", cities: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio", "Pori"] },
  { code: "FR", name: "France", cities: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Le Havre", "Saint-Étienne", "Toulon", "Grenoble", "Dijon", "Angers", "Nîmes"] },
  { code: "GA", name: "Gabon", cities: ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda"] },
  { code: "GM", name: "Gambia", cities: ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni"] },
  { code: "GE", name: "Georgia", cities: ["Tbilisi", "Kutaisi", "Batumi", "Rustavi", "Gori", "Zugdidi", "Poti"] },
  { code: "DE", name: "Germany", cities: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden", "Hanover", "Nuremberg", "Duisburg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Münster", "Karlsruhe", "Mannheim", "Augsburg"] },
  { code: "GH", name: "Ghana", cities: ["Accra", "Kumasi", "Tamale", "Takoradi", "Ashaiman", "Tema", "Cape Coast", "Sunyani", "Ho", "Koforidua"] },
  { code: "GR", name: "Greece", cities: ["Athens", "Thessaloniki", "Patras", "Piraeus", "Larissa", "Heraklion", "Volos", "Ioannina", "Chania", "Chalcis", "Serres"] },
  { code: "GD", name: "Grenada", cities: ["Saint George's", "Gouyave", "Victoria"] },
  { code: "GT", name: "Guatemala", cities: ["Guatemala City", "Mixco", "Villa Nueva", "San Juan Sacatepéquez", "Quetzaltenango", "Escuintla"] },
  { code: "GN", name: "Guinea", cities: ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé", "Guéckédou"] },
  { code: "GW", name: "Guinea-Bissau", cities: ["Bissau", "Gabú", "Bafatá", "Canchungo"] },
  { code: "GY", name: "Guyana", cities: ["Georgetown", "Linden", "New Amsterdam", "Anna Regina"] },
  { code: "HT", name: "Haiti", cities: ["Port-au-Prince", "Cap-Haïtien", "Delmas", "Pétionville", "Croix-des-Bouquets", "Gonaïves"] },
  { code: "HN", name: "Honduras", cities: ["Tegucigalpa", "San Pedro Sula", "Choloma", "El Progreso", "La Ceiba", "Villanueva"] },
  { code: "HU", name: "Hungary", cities: ["Budapest", "Debrecen", "Miskolc", "Szeged", "Pécs", "Győr", "Nyíregyháza", "Kecskemét", "Székesfehérvár"] },
  { code: "IS", name: "Iceland", cities: ["Reykjavík", "Kópavogur", "Hafnarfjörður", "Akureyri", "Reykjanesbær"] },
  { code: "IN", name: "India", cities: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Pune", "Surat", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Patna", "Vadodara", "Ghaziabad", "Ludhiana", "Coimbatore", "Agra", "Madurai", "Nashik", "Vijayawada", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivali", "Vasai-Virar", "Varanasi", "Srinagar", "Aurangabad", "Dhanbad", "Amritsar", "Navi Mumbai", "Prayagraj", "Ranchi", "Howrah", "Jabalpur", "Gwalior", "Jodhpur", "Raipur", "Kota", "Chandigarh", "Guwahati", "Thiruvananthapuram", "Mysore"] },
  { code: "ID", name: "Indonesia", cities: ["Jakarta", "Surabaya", "Medan", "Bandung", "Bekasi", "Tangerang", "Depok", "Semarang", "Palembang", "South Tangerang", "Makassar", "Batam", "Pekanbaru", "Bandar Lampung", "Malang", "Padang", "Denpasar", "Samarinda", "Tasikmalaya", "Balikpapan", "Bogor", "Manado", "Yogyakarta"] },
  { code: "IR", name: "Iran", cities: ["Tehran", "Mashhad", "Isfahan", "Karaj", "Tabriz", "Shiraz", "Qom", "Ahvaz", "Kermanshah", "Urmia", "Rasht", "Zahedan", "Hamadan", "Kerman", "Arak", "Yazd", "Qazvin"] },
  { code: "IQ", name: "Iraq", cities: ["Baghdad", "Basra", "Mosul", "Erbil", "Sulaymaniyah", "Kirkuk", "Najaf", "Karbala", "Nasiriyah", "Amarah", "Samawah", "Ramadi", "Fallujah", "Diyala"] },
  { code: "IE", name: "Ireland", cities: ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Dundalk", "Swords", "Bray", "Navan", "Kilkenny"] },
  { code: "IL", name: "Israel", cities: ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Netanya", "Beer Sheva", "Bnei Brak", "Holon", "Bat Yam"] },
  { code: "IT", name: "Italy", cities: ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania", "Venice", "Verona", "Messina", "Padua", "Trieste", "Taranto", "Brescia", "Parma", "Reggio Calabria", "Modena"] },
  { code: "JM", name: "Jamaica", cities: ["Kingston", "Spanish Town", "Portmore", "Montego Bay", "Mandeville", "May Pen"] },
  { code: "JP", name: "Japan", cities: ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kawasaki", "Kyoto", "Saitama", "Hiroshima", "Sendai", "Kitakyushu", "Chiba", "Sakai", "Kumamoto", "Sagamihara", "Hamamatsu", "Okayama", "Shizuoka", "Niigata"] },
  { code: "JO", name: "Jordan", cities: ["Amman", "Zarqa", "Irbid", "Aqaba", "Russeifa", "Quwaysimah", "Mafraq", "Madaba", "Salt", "Karak"] },
  { code: "KZ", name: "Kazakhstan", cities: ["Almaty", "Astana (Nur-Sultan)", "Shymkent", "Karaganda", "Aktobe", "Taraz", "Pavlodar", "Oskemen", "Semey", "Atyrau", "Kostanay"] },
  { code: "KE", name: "Kenya", cities: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Ruiru", "Kikuyu", "Thika", "Nyeri", "Naivasha"] },
  { code: "KI", name: "Kiribati", cities: ["Tarawa", "Betio", "Bikenibeu"] },
  { code: "KW", name: "Kuwait", cities: ["Kuwait City", "Salmiya", "Hawalli", "Fintas", "Khaitan", "Abraq Khaitan", "Al Jahra", "Sabah Al-Salem", "Mangaf", "Ahmadi", "Ar Riqqah"] },
  { code: "KG", name: "Kyrgyzstan", cities: ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok", "Uzgen"] },
  { code: "LA", name: "Laos", cities: ["Vientiane", "Pakse", "Luang Prabang", "Savannakhet", "Thakhek"] },
  { code: "LV", name: "Latvia", cities: ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala", "Ventspils"] },
  { code: "LB", name: "Lebanon", cities: ["Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh", "Zahle", "Baalbek", "Nabatieh"] },
  { code: "LS", name: "Lesotho", cities: ["Maseru", "Teyateyaneng", "Mafeteng", "Leribe"] },
  { code: "LR", name: "Liberia", cities: ["Monrovia", "Gbarnga", "Kakata", "Bensonville", "Harper"] },
  { code: "LY", name: "Libya", cities: ["Tripoli", "Benghazi", "Misrata", "Bayda", "Tobruk", "Sebha", "Zawiya"] },
  { code: "LI", name: "Liechtenstein", cities: ["Vaduz", "Schaan", "Balzers", "Triesen"] },
  { code: "LT", name: "Lithuania", cities: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Alytus"] },
  { code: "LU", name: "Luxembourg", cities: ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck"] },
  { code: "MG", name: "Madagascar", cities: ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga", "Toliara"] },
  { code: "MW", name: "Malawi", cities: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu"] },
  { code: "MY", name: "Malaysia", cities: ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh", "Shah Alam", "Petaling Jaya", "Subang Jaya", "Kota Kinabalu", "Kuching", "Malacca City", "Alor Setar", "Kota Bharu", "Klang", "Ampang Jaya", "Iskandar Puteri"] },
  { code: "MV", name: "Maldives", cities: ["Malé", "Addu City (Seenu)", "Fuvahmulah", "Kulhudhuffushi"] },
  { code: "ML", name: "Mali", cities: ["Bamako", "Sikasso", "Mopti", "Koutiala", "Kayes", "Ségou"] },
  { code: "MT", name: "Malta", cities: ["Valletta", "Birkirkara", "Qormi", "Mosta", "Żabbar", "Sliema", "San Ġwann", "Naxxar"] },
  { code: "MH", name: "Marshall Islands", cities: ["Majuro", "Ebeye"] },
  { code: "MR", name: "Mauritania", cities: ["Nouakchott", "Nouadhibou", "Rosso", "Kaédi", "Zouerate"] },
  { code: "MU", name: "Mauritius", cities: ["Port Louis", "Vacoas-Phoenix", "Beau Bassin-Rose Hill", "Curepipe", "Quatre Bornes"] },
  { code: "MX", name: "Mexico", cities: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "Juárez", "León", "Zapopan", "Mérida", "San Luis Potosí", "Aguascalientes", "Hermosillo", "Mexicali", "Culiacán", "Acapulco", "Jalapa", "Querétaro", "Chihuahua", "Morelia", "Cancún"] },
  { code: "FM", name: "Micronesia", cities: ["Palikir", "Weno", "Kolonia"] },
  { code: "MD", name: "Moldova", cities: ["Chișinău", "Tiraspol", "Bălți", "Bender", "Rîbnița"] },
  { code: "MC", name: "Monaco", cities: ["Monaco"] },
  { code: "MN", name: "Mongolia", cities: ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Ölgii"] },
  { code: "ME", name: "Montenegro", cities: ["Podgorica", "Nikšić", "Pljevlja", "Bijelo Polje", "Herceg Novi"] },
  { code: "MA", name: "Morocco", cities: ["Casablanca", "Fez", "Marrakech", "Rabat", "Tangier", "Agadir", "Meknès", "Oujda", "Kenitra", "Tetouan", "Safi", "Beni Mellal", "Khouribga", "El Jadida"] },
  { code: "MZ", name: "Mozambique", cities: ["Maputo", "Matola", "Beira", "Nampula", "Chimoio", "Nacala", "Quelimane", "Tete"] },
  { code: "MM", name: "Myanmar", cities: ["Naypyidaw", "Yangon", "Mandalay", "Mawlamyine", "Bago", "Pathein", "Taunggyi", "Sittwe"] },
  { code: "NA", name: "Namibia", cities: ["Windhoek", "Rundu", "Walvis Bay", "Swakopmund", "Oshakati"] },
  { code: "NR", name: "Nauru", cities: ["Yaren", "Denigomodu", "Aiwo"] },
  { code: "NP", name: "Nepal", cities: ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Bharatpur", "Birgunj", "Dharan", "Butwal", "Hetauda", "Nepalgunj"] },
  { code: "NL", name: "Netherlands", cities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere", "Breda", "Nijmegen", "Enschede", "Apeldoorn", "Haarlem", "Maastricht", "Leiden", "Dordrecht"] },
  { code: "NZ", name: "New Zealand", cities: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Napier-Hastings", "Dunedin", "Palmerston North", "Nelson", "Rotorua", "New Plymouth"] },
  { code: "NI", name: "Nicaragua", cities: ["Managua", "León", "Masaya", "Matagalpa", "Chinandega", "Estelí", "Granada"] },
  { code: "NE", name: "Niger", cities: ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Dosso"] },
  { code: "NG", name: "Nigeria", cities: ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Maiduguri", "Zaria", "Aba", "Jos", "Ilorin", "Oyo", "Enugu", "Abeokuta", "Kaduna", "Nnewi", "Ogbomosho", "Warri", "Calabar", "Uyo", "Akure", "Sokoto", "Owerri"] },
  { code: "KP", name: "North Korea", cities: ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan"] },
  { code: "MK", name: "North Macedonia", cities: ["Skopje", "Bitola", "Kumanovo", "Tetovo", "Veles", "Gostivar"] },
  { code: "NO", name: "Norway", cities: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Kristiansand", "Fredrikstad", "Tromsø", "Sandnes", "Asker", "Bærum"] },
  { code: "OM", name: "Oman", cities: ["Muscat", "Seeb", "Salalah", "Bawshar", "Sohar", "Nizwa", "Sur", "Ibra", "Khasab", "As Suwayq"] },
  { code: "PK", name: "Pakistan", cities: ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Faisalabad", "Multan", "Peshawar", "Quetta", "Gujranwala", "Sialkot", "Hyderabad", "Sargodha", "Bahawalpur", "Sukkur", "Larkana", "Sheikhupura", "Jhang", "Rahim Yar Khan", "Gujrat", "Wah Cantonment", "Mardan", "Abbottabad", "Muzaffarabad", "Mirpur", "Chiniot", "Dera Ghazi Khan", "Sahiwal", "Okara", "Mingora", "Nawabshah"] },
  { code: "PW", name: "Palau", cities: ["Ngerulmud", "Koror"] },
  { code: "PS", name: "Palestine", cities: ["Gaza City", "Hebron", "Ramallah", "Nablus", "Jenin", "Tulkarm", "Qalqilya", "Bethlehem", "Jericho", "Rafah"] },
  { code: "PA", name: "Panama", cities: ["Panama City", "San Miguelito", "Tocumen", "David", "Arraiján", "La Chorrera", "Colón"] },
  { code: "PG", name: "Papua New Guinea", cities: ["Port Moresby", "Lae", "Mount Hagen", "Popondetta", "Madang"] },
  { code: "PY", name: "Paraguay", cities: ["Asunción", "Ciudad del Este", "San Lorenzo", "Luque", "Capiatá", "Lambaré", "Fernando de la Mora", "Encarnación"] },
  { code: "PE", name: "Peru", cities: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cusco", "Huancayo", "Chimbote", "Puno", "Tacna", "Juliaca", "Ica"] },
  { code: "PH", name: "Philippines", cities: ["Manila", "Quezon City", "Caloocan", "Davao", "Cebu City", "Zamboanga City", "Antipolo", "Taguig", "Pasig", "Cagayan de Oro", "Makati", "Parañaque", "Las Piñas", "Bacolod", "Iloilo City", "Marikina", "Valenzuela", "Pasay", "General Santos", "Muntinlupa"] },
  { code: "PL", name: "Poland", cities: ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Katowice", "Białystok", "Gdynia", "Częstochowa", "Radom", "Sosnowiec", "Toruń", "Kielce", "Gliwice", "Zabrze"] },
  { code: "PT", name: "Portugal", cities: ["Lisbon", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Funchal", "Setúbal", "Coimbra", "Almada", "Agualva-Cacém", "Aveiro", "Faro"] },
  { code: "QA", name: "Qatar", cities: ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Al Shamal", "Madinat ash Shamal", "Dukhan", "Mesaieed", "Lusail"] },
  { code: "RO", name: "Romania", cities: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Brașov", "Galați", "Ploiești", "Oradea", "Brăila", "Bacău", "Arad", "Sibiu", "Pitești"] },
  { code: "RU", name: "Russia", cities: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Ufa", "Rostov-on-Don", "Krasnoyarsk", "Perm", "Voronezh", "Volgograd", "Saratov", "Krasnodar", "Tyumen", "Tolyatti", "Izhevsk", "Barnaul", "Irkutsk", "Khabarovsk", "Vladivostok", "Makhachkala", "Tomsk", "Kemerovo"] },
  { code: "RW", name: "Rwanda", cities: ["Kigali", "Butare", "Gitarama", "Musanze", "Gisenyi"] },
  { code: "KN", name: "Saint Kitts and Nevis", cities: ["Basseterre", "Charlestown"] },
  { code: "LC", name: "Saint Lucia", cities: ["Castries", "Bisee", "Vieux Fort"] },
  { code: "VC", name: "Saint Vincent and the Grenadines", cities: ["Kingstown", "Georgetown", "Barrouallie"] },
  { code: "WS", name: "Samoa", cities: ["Apia", "Vaitele", "Faleolo"] },
  { code: "SM", name: "San Marino", cities: ["San Marino City", "Serravalle"] },
  { code: "ST", name: "São Tomé and Príncipe", cities: ["São Tomé", "Santo António"] },
  { code: "SA", name: "Saudi Arabia", cities: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Taif", "Tabuk", "Buraidah", "Abha", "Khamis Mushait", "Hail", "Hofuf", "Al Mubarraz", "Najran", "Jizan", "Yanbu", "Jubail", "Al Qatif", "Qassim"] },
  { code: "SN", name: "Senegal", cities: ["Dakar", "Touba", "Thiès", "Saint-Louis", "Kaolack", "Ziguinchor", "Diourbel"] },
  { code: "RS", name: "Serbia", cities: ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin", "Pančevo", "Čačak", "Novi Pazar"] },
  { code: "SC", name: "Seychelles", cities: ["Victoria", "Anse Boileau", "Beau Vallon"] },
  { code: "SL", name: "Sierra Leone", cities: ["Freetown", "Bo", "Kenema", "Makeni", "Koidu"] },
  { code: "SG", name: "Singapore", cities: ["Singapore"] },
  { code: "SK", name: "Slovakia", cities: ["Bratislava", "Košice", "Prešov", "Nitra", "Žilina", "Banská Bystrica", "Trnava"] },
  { code: "SI", name: "Slovenia", cities: ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper"] },
  { code: "SB", name: "Solomon Islands", cities: ["Honiara", "Gizo", "Auki"] },
  { code: "SO", name: "Somalia", cities: ["Mogadishu", "Hargeisa", "Kismayo", "Merca", "Bosaso", "Berbera"] },
  { code: "ZA", name: "South Africa", cities: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Pietermaritzburg", "Bloemfontein", "Soweto", "East London", "Vereeniging", "Tshwane", "Witbank", "Polokwane", "Nelspruit", "Kimberley"] },
  { code: "KR", name: "South Korea", cities: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Seongnam", "Goyang", "Bucheon", "Ansan", "Cheongju", "Jeonju", "Anyang", "Pohang", "Jeju City"] },
  { code: "SS", name: "South Sudan", cities: ["Juba", "Wau", "Malakal", "Yei", "Rumbek"] },
  { code: "ES", name: "Spain", cities: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Murcia", "Palma", "Las Palmas", "Bilbao", "Alicante", "Córdoba", "Valladolid", "Vigo", "Gijón", "L'Hospitalet", "A Coruña", "Vitoria-Gasteiz", "Granada", "Elche"] },
  { code: "LK", name: "Sri Lanka", cities: ["Colombo", "Dehiwala-Mount Lavinia", "Moratuwa", "Jaffna", "Negombo", "Kandy", "Gampaha", "Kurunegala", "Trincomalee", "Galle", "Batticaloa"] },
  { code: "SD", name: "Sudan", cities: ["Khartoum", "Omdurman", "Khartoum North", "Port Sudan", "Kassala", "Obeid", "Wad Madani", "Atbara", "El Fasher"] },
  { code: "SR", name: "Suriname", cities: ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo"] },
  { code: "SE", name: "Sweden", cities: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Solna", "Västerås", "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping", "Lund", "Umeå", "Gävle", "Borås"] },
  { code: "CH", name: "Switzerland", cities: ["Zürich", "Geneva", "Basel", "Lausanne", "Bern", "Winterthur", "Lucerne", "St. Gallen", "Lugano", "Biel/Bienne", "Thun"] },
  { code: "SY", name: "Syria", cities: ["Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Deir ez-Zor", "Al-Hasakah", "Qamishli", "Raqqa"] },
  { code: "TW", name: "Taiwan", cities: ["Taipei", "New Taipei", "Taichung", "Kaohsiung", "Taoyuan", "Tainan", "Hsinchu", "Keelung"] },
  { code: "TJ", name: "Tajikistan", cities: ["Dushanbe", "Khujand", "Kulob", "Qurghonteppa", "Istaravshan"] },
  { code: "TZ", name: "Tanzania", cities: ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma", "Mbeya", "Morogoro", "Tanga", "Kahama", "Tabora", "Zanzibar City"] },
  { code: "TH", name: "Thailand", cities: ["Bangkok", "Nonthaburi", "Nakhon Ratchasima", "Chiang Mai", "Hat Yai", "Khon Kaen", "Pak Kret", "Udon Thani", "Surat Thani", "Pattaya", "Phuket", "Rayong", "Chonburi"] },
  { code: "TL", name: "Timor-Leste", cities: ["Dili", "Baucau", "Maliana"] },
  { code: "TG", name: "Togo", cities: ["Lomé", "Sokodé", "Kara", "Atakpamé", "Kpalimé", "Dapaong"] },
  { code: "TO", name: "Tonga", cities: ["Nuku'alofa", "Neiafu"] },
  { code: "TT", name: "Trinidad and Tobago", cities: ["Port of Spain", "Chaguanas", "San Fernando", "Arima", "Point Fortin", "Scarborough"] },
  { code: "TN", name: "Tunisia", cities: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabès", "Ariana", "Gafsa", "Monastir", "Ben Arous", "Nabeul"] },
  { code: "TR", name: "Turkey", cities: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Gaziantep", "Konya", "Mersin", "Kayseri", "Eskişehir", "Diyarbakır", "Samsun", "Denizli", "Şanlıurfa", "Malatya", "Trabzon", "Adapazarı", "Kahramanmaraş", "Gebze", "Erzurum"] },
  { code: "TM", name: "Turkmenistan", cities: ["Ashgabat", "Türkmenabat", "Daşoguz", "Mary", "Balkanabat"] },
  { code: "TV", name: "Tuvalu", cities: ["Funafuti"] },
  { code: "UG", name: "Uganda", cities: ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja", "Bwizibwera", "Mbale", "Mukono"] },
  { code: "UA", name: "Ukraine", cities: ["Kyiv", "Kharkiv", "Odessa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv", "Kryvyi Rih", "Mykolaiv", "Mariupol", "Poltava", "Vinnytsia", "Chernivtsi", "Kherson", "Khmelnytskyi", "Cherkasy", "Zhytomyr", "Sumy", "Rivne", "Ternopil"] },
  { code: "AE", name: "United Arab Emirates", cities: ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain", "Khor Fakkan", "Jebel Ali", "Al Quoz", "Deira"] },
  { code: "GB", name: "United Kingdom", cities: ["London", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Leeds", "Sheffield", "Edinburgh", "Bristol", "Cardiff", "Leicester", "Bradford", "Coventry", "Nottingham", "Hull", "Newcastle upon Tyne", "Stoke-on-Trent", "Southampton", "Plymouth", "Reading", "Belfast", "Derby", "Wolverhampton", "Sunderland", "Swansea", "Brighton", "Milton Keynes", "Oxford", "Cambridge"] },
  { code: "US", name: "United States", cities: ["New York City", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "San Francisco", "Indianapolis", "Seattle", "Denver", "Washington DC", "Nashville", "Oklahoma City", "El Paso", "Las Vegas", "Louisville", "Portland", "Memphis", "Baltimore", "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Sacramento", "Mesa", "Atlanta", "Kansas City", "Omaha", "Colorado Springs", "Raleigh", "Miami", "Boston", "Minneapolis", "Detroit", "San Luis Obispo", "Tampa", "New Orleans", "Cleveland", "Orlando", "Pittsburgh"] },
  { code: "UY", name: "Uruguay", cities: ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandú", "Las Piedras", "Rivera", "Maldonado"] },
  { code: "UZ", name: "Uzbekistan", cities: ["Tashkent", "Samarkand", "Namangan", "Andijan", "Bukhara", "Qashqadaryo", "Fergana", "Guliston", "Nukus", "Margilon"] },
  { code: "VU", name: "Vanuatu", cities: ["Port Vila", "Luganville"] },
  { code: "VE", name: "Venezuela", cities: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana", "Barcelona", "Maturín", "Cumaná", "Petare", "Barinas", "Ciudad Bolívar"] },
  { code: "VN", name: "Vietnam", cities: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Bien Hoa", "Hue", "Nha Trang", "Can Tho", "Thu Duc", "Vung Tau", "Quy Nhon", "Da Lat", "Buon Ma Thuot", "Thai Nguyen", "Long Xuyen"] },
  { code: "YE", name: "Yemen", cities: ["Sanaa", "Aden", "Taiz", "Hodeidah", "Mukalla", "Ibb", "Dhamar", "Amran", "Sayyan"] },
  { code: "ZM", name: "Zambia", cities: ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Mufulira", "Livingstone", "Luanshya"] },
  { code: "ZW", name: "Zimbabwe", cities: ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Kwekwe", "Kadoma", "Masvingo", "Chinhoyi"] },
];

export const COUNTRY_MAP = new Map<string, Country>(
  COUNTRIES.map((c) => [c.code, c])
);

export function getCitiesForCountry(code: string): string[] {
  return COUNTRY_MAP.get(code)?.cities ?? [];
}

export function getCountryName(code: string): string {
  return COUNTRY_MAP.get(code)?.name ?? code;
}
