#!/bin/bash
set -euo pipefail

echo '{"async": true, "asyncTimeout": 300000}'

# Only run in remote (Claude Code on the web) environments
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

cd "${CLAUDE_PROJECT_DIR:-/home/user/xplosale}"

# ── 1. Bootstrap .env if missing ─────────────────────────────────────────────
# This is required by docker-compose (env_file: .env).
# We generate safe random secrets and use the local Docker service hostnames.
if [ ! -f .env ]; then
  echo "[session-start] .env not found — generating from template..."
  NEXTAUTH_SECRET=$(openssl rand -base64 32)
  CNIC_HASH_SALT=$(openssl rand -base64 32)
  cat > .env <<ENVFILE
# Auto-generated by session-start hook ($(date -u +%Y-%m-%dT%H:%M:%SZ))
# Edit this file to override any value.

# ── Database (local Docker postgres service) ──────────────────────────────────
DATABASE_URL="postgresql://xplosale:xplosale2024@postgres:5432/xplosale"
DIRECT_URL="postgresql://xplosale:xplosale2024@postgres:5432/xplosale"

# ── NextAuth ──────────────────────────────────────────────────────────────────
NEXTAUTH_SECRET="${NEXTAUTH_SECRET}"
NEXTAUTH_URL="http://localhost:3000"

# ── Storage (local filesystem — no S3 credentials needed) ────────────────────
STORAGE_MODE="local"
SUPABASE_S3_REGION="ap-southeast-1"
SUPABASE_PUBLIC_BUCKET="xplosale-public"
SUPABASE_PRIVATE_BUCKET="xplosale-private"

# ── Redis (local Docker redis service) ───────────────────────────────────────
UPSTASH_REDIS_URL="redis://redis:6379"

# ── Security ──────────────────────────────────────────────────────────────────
CNIC_HASH_SALT="${CNIC_HASH_SALT}"

# ── Google OAuth (optional) ───────────────────────────────────────────────────
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""

# ── Email (optional — logs to console when blank) ─────────────────────────────
EMAIL_SERVER=""
EMAIL_FROM="noreply@xplosale.com"
RESEND_API_KEY=""

# ── App ───────────────────────────────────────────────────────────────────────
NEXT_PUBLIC_APP_URL="http://localhost:3000"
NODE_ENV="production"
ENVFILE
  echo "[session-start] .env created."
fi

# ── 2. Install Node dependencies (also triggers prisma generate via postinstall)
echo "[session-start] Installing Node dependencies..."
corepack enable pnpm 2>/dev/null || true
pnpm install --frozen-lockfile 2>&1 | tail -5

echo "[session-start] Done."
